---
title: "linear models"
output: github_document
---

```{r setup, include=FALSE, message = FALSE, warning = FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  echo = TRUE, 
  warning = FALSE,
  fig.width = 6, 
  fig.asp = .6, 
  out.width = "90%"
  )

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
```

Load key packages. 
```{r cars}
library(tidyverse)
library(p8105.datasets)
```


Set seed for reproducibility.
```{r}
set.seed(1)
```

## Load Airbnb Data

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(stars = review_scores_location / 2) |> 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) |> 
  filter(borough != "Staten Island") |> 
  select(price, stars, borough, neighborhood, room_type)
  
```

Let's fit a model!

```{r}
fit =
  nyc_airbnb |> 
  lm(price ~ stars + borough, data = _)
```

Let's look at the `fit`

```{r}
summary(fit)
summary(fit)$coef
coef(fit)
fitted.values(fit)
```

tidy up the output instead

```{r}
fit |> 
  broom::glance()
```


tidy up the coefficients 

```{r}
fit |> 
  broom::tidy() |> 
  mutate(term = str_replace(term, "^borough", "Borough:")) |> 
  select(term, estimate, p.value) |> 
  knitr::kable(digits = 3)
```


## Fit another model 

```{r}
fit =
  nyc_airbnb |> 
  mutate(
    borough = fct_infreq(borough),
    room_type = fct_infreq(room_type)
  ) |> 
  lm(price ~ stars + borough + room_type, data = _)

fit |> 
  broom::tidy()
```


## Quick look at diagnostics

```{r}
nyc_airbnb |> 
  modelr::add_residuals(fit) |> 
  ggplot(aes(x = resid)) +
  geom_density() +
  xlim(-100, 500)

nyc_airbnb |> 
  modelr::add_residuals(fit) |> 
  ggplot(aes(x = borough, y = resid)) +
  geom_violin()

nyc_airbnb |> 
  modelr::add_residuals(fit) |> 
  ggplot(aes(x = stars, y = resid)) +
  geom_point()
```

## Hypothesis test for categorical predictor

fit a "null" and "alternative" model

```{r}
fit_null = lm(price ~ stars + borough, data = nyc_airbnb)
fit_alternative = lm(price ~ stars + borough + room_type, data = nyc_airbnb)

anova(fit_null, fit_alternative) |> 
  broom::tidy()
```



## Borough-level differences

```{r}
fit =
  nyc_airbnb |> 
  lm(price = stars * borough + room_type * borough, data = _)

fit |> 
  broom::tidy()
```



```{r}
airbnb_lm = function(df) {
  lm(price ~ stars + room_type, data = df)
}

nyc_airbnb |> 
  nest(df = -borough) |> 
  mutate(
    models = map(df, airbnb_lm), 
    results = map(models, broom::tidy)
  ) |> 
  select(borough, results) |> 
  unnest(results) |> 
  select(borough, term, estimate) |> 
  pivot_wider(
    names_from = term, 
    values_from = estimate
  ) |> 
  knitr::kable(digits = 2)
```


same thing, just a little different
```{r}
nyc_airbnb |> 
  nest(df = -borough) |> 
  mutate(
    models = map(df, \(df) lm(price ~ stars + room_type, data = df)), 
    results = map(models, broom::tidy)
  ) |> 
  select(borough, results) |> 
  unnest(results) |> 
  select(borough, term, estimate) |> 
  pivot_wider(
    names_from = term, 
    values_from = estimate
  ) |> 
  knitr::kable(digits = 2)
```

